apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
      - name: test-app
        image: aduka27/model:ca451e8
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  selector:
    app: python-service
  ports:
  - port: 80
