name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          GIT_TAG=$(git rev-parse --short=7 HEAD)
          docker login -u aduka27 -p ${{ secrets.PASS }}
          docker build -t aduka27/model:$GIT_TAG .
          docker tag aduka27/model:$GIT_TAG aduka27/model:latest
          docker push aduka27/model:$GIT_TAG
          docker push aduka27/model:latest
          sed -i 's/latest/$GIT_TAG/g deployments/test.yaml
          cat deployments/test.yaml

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
